- name: "Create sdt dir"
  become: true
  ansible.builtin.command:
    cmd: mkdir /usr/share/sddm/themes/sdt
    creates: /usr/share/sddm/themes/sdt/

- name: Chown
  become: true
  file:
    path: /usr/share/sddm/themes/sdt
    state: directory
    owner: raiden
    group: raiden
    recurse: true

- name: Copy sddm theme
  copy:
    src: ~/arch-config/sddm/themes/sdt/
    dest: /usr/share/sddm/themes/sdt
    mode: "755"

- name: "Create config dir"
  become: true
  ansible.builtin.command:
    cmd: mkdir /etc/sddm.conf.d/
    creates: /etc/sddm.conf.d/

- name: Copy theme conf
  become: true
  copy:
    src: ~/arch-config/sddm/10-theme.conf
    dest: /etc/sddm.conf.d/
    mode: "644"

- name: Create sessions
  become: true
  ansible.builtin.command:
    cmd: mkdir /usr/share/wayland-sessions
    creates: /usr/share/wayland-sessions

- name: Copy hypr.desktop
  copy:
    src: ~/arch-config/sddm/hyprland.desktop
    dest: /usr/share/wayland-sessions/
    mode: "644"
