- name: Create dev dir
  become: true
  command:
    cmd: mkdir /opt/dev/
  changed_when: false

- name: Abitype
  become: true
  ansible.builtin.git:
    repo: https://github.com/wagmi-dev/abitype
    dest: /opt/dev/abitype

- name: Grub menu
  become: true
  ansible.builtin.git:
    repo: https://github.com/semimqmo/sekiro_grub_theme
    dest: /opt/dev/grub_sekiro

- name: Install grub menu
  become: true
  command:
    cmd: /opt/dev/grub_sekiro/install.sh
  changed_when: false

- name: Tmux tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm/

- name: Chown
  become: true
  file:
    path: /opt/dev
    state: directory
    owner: raiden
    group: raiden
    recurse: true
