#!/bin/bash

export CC=gcc-12 CXX=g++-12

paru -S sddm-sugar-candy-git --noconfirm
paru -S waybar-hyprland --noconfirm
paru -S spotify-player --noconfirm
paru -S tela-circle-icon-theme-dracula-git --noconfirm
