#!/bin/bash

# setup the first look and feel as dark
xfconf-query -c xsettings -p /Net/ThemeName -s Catppuccin-Mocha-Standart-Mauve-Dark
xfconf-query -c xsettings -p /Net/IconThemeName -s "Tela circle dracula dark"
gsettings set org.gnome.desktop.interface gtk-theme Catppuccin-Mocha-Standart-Mauve-Dark
gsettings set org.gnome.desktop.interface icon-theme "Tela circle dracula dark"
gsettings set org.gnome.desktop.interface cursor-theme "Bibata Modern Ice"

# Install Bun
curl -fsSL https://bun.sh/install | bash

# Install Foundry
curl -L https://foundry.paradigm.xyz | bash

# Configure Fish
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
cat ~/.config/fish/fish_plugins | fisher install $1

# Install pnpm
bun add -g pnpm

# Configure ZVM
curl https://raw.githubusercontent.com/tristanisham/zvm/master/install.sh | bash

# Install ZIG/ZLS
$HOME/.zvm/self/zvm i master
$HOME/.zvm/self/zvm i -D=zls master

chsh -s /usr/bin/fish

sudo systemctl start sddm
