- name: Install packages
  become: true
  pacman:
    name:
      - curl
      - discord
      - eza
      - paru
      - gcc12
      - qt5-wayland
      - qt5ct
      - qt5-quickcontrols
      - qt5-imageformats
      - qt6-wayland
      - qt6ct
      - gtk3
      - polkit-gnome
      - pipewire
      - wireplumber
      - jq
      - wl-clipboard
      - github-cli
      - cliphist
      - python-requests
      - pacman-contrib
      - kitty
      - mako
      - swww
      - swaylock-effects
      - wofi
      - wlogout
      - xdg-desktop-portal-hyprland
      - swappy
      - grim
      - slurp
      - thunar
      - btop
      - firefox
      - mpv
      - pamixer
      - pavucontrol
      - network-manager-applet
      - gvfs
      - thunar-archive-plugin
      - file-roller
      - starship
      - papirus-icon-theme
      - ttf-jetbrains-mono-nerd
      - noto-fonts-emoji
      - lxappearance
      - xfce4-settings
      - nwg-look-bin
      - sddm-git
      - catppuccin-gtk-theme-mocha
      - catppuccin-gtk-theme-latte
      - bibata-cursor-theme
      - fish
      - fzf
      - neovim
      - brave-bin
      - inetutils
      - vscodium
      - neofetch
      - pokemon-colorscripts-git
      - cava
      - steam
      - lutris
      - tmux
      - wine-stable
      - telegram-desktop
      - ripgrep
      - qbittorrent
      - signal-desktop
      - dotnet-runtime
      - dotnet-sdk
      - hyprland
