- name: Install packages
  become: true
  pacman:
    name:
      - curl
      - discord
      - eza
      - paru
      - bat
      - otf-cascadia-code
      - ttf-cascadia-code
      - gcc12
      - go
      - qt5-wayland
      - qt5ct
      - gedit
      - qt5-quickcontrols
      - qt5-imageformats
      - qt6-wayland
      - qt6ct
      - gtk3
      - gtk4
      - polkit-gnome
      - pipewire
      - wireplumber
      - vulkan-radeon
      - libva-mesa-driver
      - mangohud-git
      - jq
      - wl-clipboard
      - github-cli
      - cliphist
      - python-requests
      - pacman-contrib
      - kitty
      - mako
      - swww
      - swaylock-effects
      - wofi
      - wlogout
      - xdg-desktop-portal-hyprland
      - swappy
      - grim
      - slurp
      - thunar
      - btop
      - firefox
      - mpv
      - pamixer
      - pavucontrol
      - network-manager-applet
      - gvfs
      - thunar-archive-plugin
      - file-roller
      - starship
      - papirus-icon-theme
      - ttf-jetbrains-mono-nerd
      - noto-fonts-emoji
      - lxappearance
      - xfce4-settings
      - nwg-look-bin
      - sddm-git
      - catppuccin-gtk-theme-mocha
      - catppuccin-gtk-theme-latte
      - bibata-cursor-theme
      - fish
      - fzf
      - neovim
      - brave-bin
      - inetutils
      - vscodium
      - neofetch
      - pokemon-colorscripts-git
      - cava
      - steam
      - lutris
      - tmux
      - wine-stable
      - telegram-desktop
      - ripgrep
      - qbittorrent
      - signal-desktop
      - dotnet-runtime
      - dotnet-sdk
      - less
      - fnm
      - python-pip
      - fd
      - hyprland

- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: "644"
    validate: 'visudo -cf %s'

- name: Run aur script
  become: true
  become_user: aur_builder
  ansible.builtin.script:
    cmd: ~/arch-config/ansible/post-ansible
