- name: "Create config dir"
  file:
    path: ~/.config/
    state: directory
    mode: "644"

- name: "Find config files"
  find:
    paths: ~/arch-config/dotfiles/
    recurse: false
    file_type: any
    hidden: true
  register: dot_config

- name: "Copy config files"
  file:
    src: "{{ item.path }}"
    dest: "~/.config/{{ item.path | basename }}"
    state: link
  loop: "{{ dot_config.files }}"

- name: Gitconfig
  file:
    src: ~/.config/.gitconfig
    dest: ~/.gitconfig
    state: link

- name: Tmux
  file:
    src: ~/.config/.tmux.conf
    dest: ~/.tmux.conf
    state: link

- name: Scripts
  file:
    src: ~/arch-config/scripts
    dest: ~/.scripts
    state: link

- name: Gpg agent
  copy:
    dest: ~/.gnupg/gpg-agent.conf
    content: "pinentry-program /bin/pinentry"
    mode: "644"

- name: Ssh config
  copy:
    src: ~/.config/.ssh.config
    dest: ~/.ssh/config
    mode: u=rw,o=,g=

- name: Ssh control config
  file:
    path: ~/.ssh/control
    state: directory
    mode: u=rwx,o=,g=
